#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Kółko i krzyżyk
Komputer gra w kółko i krzyżyk przeciwko człowiekowi
"""

# stałe globalne
X = "X"
O = "O"
EMPTY = " "
TIE = "TIE"
NUM_SQUARES = 9

# wyświetla zasady gry i obsługi programu
def display_instruct():

# odebranie od użytkownika decyzji, kto powinien rozpocząć grę
def ask_yes_no(question):

# zadanie pytania użytkownikowi, pole o którym numerze, chce zająć
# posiada system zabezpieczający przed podaniem liczby spoza zakresu
def ask_number(question, low, high):

# ustalenie do kogo należy ruch i przypisanie graczowi odpowiedniego znaku (X lub O)
def pieces():

# wyświetla planszę do gry
def display_board(board):

# komunikat o błędnym ruchu
def false_move():

# komunikat o poprawnym ruchu
def move_accepted():

# podanie informacji o ruchu komputera
def print_computer_move(move):

# wyświetla wynik gry
def congrat_winner(the_winner, computer, human):

"""
/ \
 |
 Funkcje odpowiadające za komunikację z użytkownikiem

#############################################################################################

Funkcje odpowiadające, za właściwą grę
 |
\ /
"""

# tworzy nową planszę do gry
def new_board():

# sprawdza dozwolone ruchy na zadanej planszy
def legal_moves(board):

# sprawdza wynik gry, decyduje także o remisie
def winner(board):

# odpowiada za przepisanie danych podanych od użytkownika to komputerowej reprezentacji planszy
def human_move(board, human):

# implementacja algorytmu otpowiadającego za grę komputera
def computer_move(board, computer, human):
  """Spowoduj wykonanie ruchu przez komputer."""
    # utwórz kopię roboczą, ponieważ funkcja będzie zmieniać listę
    board = board[:]
    # najlepsze pozycje do zajęcia według kolejności
    BEST_MOVES = (4, 0, 2, 6, 8, 1, 3, 5, 7)

    print("Wybieram pole numer", end=" ")
    
    # jeśli komputer może wygrać, wykonaj ten ruch
    for move in legal_moves(board):
        board[move] = computer
        if winner(board) == computer:
            print(move)
            return move
        # ten ruch został sprawdzony, wycofaj go
        board[move] = EMPTY

# zmiana wykonawcy ruchu
def next_turn(turn):



# main
def main():truct()
    computer, human = pieces()
    turn = X
    board = new_board()
    display_board(board)

    while not winner(board):
        if turn == human:
            move = human_move(board, human)
            board[move] = human
        else:
            move = computer_move(board, computer, human)
            board[move] = computer
        display_board(board)
        turn = next_turn(turn)

    the_winner = winner(board)
    congrat_winner(the_winner, computer, human)

# rozpocznij program
main()
input("\n\nAby zakończyć grę, naciśnij klawisz Enter.")
